### ISSUE TITLE
Research Satellite Hardware Solutions

### ISSUE THREAD

**Issue by hhenry01** [UBCSailbot/tasks#23]
### Purpose

We need some method of transmitting data to and from the boat on the water. [This is the satellite being used for Raye](https://www.groundcontrol.com/en/product/rockblock-plus-waterproof-satellite-iot-device/). Unfortunately, even reusing the hardware is not simple. Due to the lack of documentation on how it was set up for Raye, we would functionally be starting from scratch anyways. Hence, we should look for alternative solutions as well.

### Resources

[Raye satellite Confluence pages](https://ubcsailbot.atlassian.net/wiki/spaces/ADA2/pages/1234356/Satellite+Modem+Antenna) - pretty lacking and disorganized unfortunately

**Comment by colinli02** [comment]
Based on the last net meeting we decided to use the same hardware as last time

[Reference meeting notes](https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1802404083/2023-01-28+NET+Meeting+Notes)
